mysql: &mysql
  adapter: mysql2
  database: redmine_test
  username: root
  encoding: utf8

postgres: &postgresql
  adapter: postgresql
  database: redmine_test
  username: postgres

sqlite: &sqlite
  adapter: sqlite3
  database: "<%= ENV['HOME'] %>/rmonitor_test.sqlite3"
  timeout: 500

test:
    <<: *<%= ENV['DB'] || 'sqlite' %>