#!/usr/bin/env ruby

require_relative '../lib/rmonitor/cli'

begin
  cli = RMonitor::CLI.instance
  cli.start
rescue => e
  raise e if $DEBUG
  STDERR.puts e.message
  STDERR.puts e.backtrace.join("\n")
  exit 1
end
